select_origin: directory
files_origin: ../../temp/
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ../../temp/
history: false
focus_max: 2
record_types:
  undefined:
    stroke: "#eeeeee"
    fill: "#eeeeee"
  personne:
    stroke: "#d7191c"
    fill: "#d7191c"
  Å“uvre:
    stroke: "#fdae61"
    fill: "#fdae61"
  institution:
    stroke: "#abd9e9"
    fill: "#abd9e9"
  otlet:
    stroke: "#2c7bb6"
    fill: "#2c7bb6"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  adjacent concept:
    stroke: dotted
    color: "#e1e1e1"
references_as_nodes: false
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 7
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 10
attraction_force: 600
attraction_distance_max: 600
attraction_vertical: 0
attraction_horizontal: 0
hide_id_from_record_header: false
views: {}
record_metas: []
title: "Cosma demo: batch"
author: ""
description: ""
keywords: []
link_symbol: ""
link_context: inline
devtools: false
lang: fr
name: ""
generate_id: never